//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anchi.ERP.Common.Globalization
{
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CountryDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryDisplayNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anchi.ERP.Common.Globalization.CountryDisplayNames", typeof(CountryDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 APO/FPO 的本地化字符串。
        /// </summary>
        public static string AA {
            get {
                return ResourceManager.GetString("AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANDORRA 的本地化字符串。
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UNITED ARAB EMIRATES 的本地化字符串。
        /// </summary>
        public static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AFGHANISTAN 的本地化字符串。
        /// </summary>
        public static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANTIGUA AND BARBUDA 的本地化字符串。
        /// </summary>
        public static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANGUILLA 的本地化字符串。
        /// </summary>
        public static string AI {
            get {
                return ResourceManager.GetString("AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALBANIA 的本地化字符串。
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ARMENIA 的本地化字符串。
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANGOLA 的本地化字符串。
        /// </summary>
        public static string AO {
            get {
                return ResourceManager.GetString("AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANTARCTICA 的本地化字符串。
        /// </summary>
        public static string AQ {
            get {
                return ResourceManager.GetString("AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ARGENTINA 的本地化字符串。
        /// </summary>
        public static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AMERICAN SAMOA 的本地化字符串。
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AUSTRIA 的本地化字符串。
        /// </summary>
        public static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AUSTRALIA 的本地化字符串。
        /// </summary>
        public static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ARUBA 的本地化字符串。
        /// </summary>
        public static string AW {
            get {
                return ResourceManager.GetString("AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALAND ISLANDS 的本地化字符串。
        /// </summary>
        public static string AX {
            get {
                return ResourceManager.GetString("AX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AZERBAIJAN 的本地化字符串。
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOSNIA AND HERZEGOVINA 的本地化字符串。
        /// </summary>
        public static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BARBADOS 的本地化字符串。
        /// </summary>
        public static string BB {
            get {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BANGLADESH 的本地化字符串。
        /// </summary>
        public static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BELGIUM 的本地化字符串。
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BURKINA FASO 的本地化字符串。
        /// </summary>
        public static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BULGARIA 的本地化字符串。
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BAHRAIN 的本地化字符串。
        /// </summary>
        public static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BURUNDI 的本地化字符串。
        /// </summary>
        public static string BI {
            get {
                return ResourceManager.GetString("BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BENIN 的本地化字符串。
        /// </summary>
        public static string BJ {
            get {
                return ResourceManager.GetString("BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAINT BARTHELEMY 的本地化字符串。
        /// </summary>
        public static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BERMUDA 的本地化字符串。
        /// </summary>
        public static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BRUNEI DARUSSALAM 的本地化字符串。
        /// </summary>
        public static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOLIVIA, PLURINATIONAL STATE OF 的本地化字符串。
        /// </summary>
        public static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BONAIRE, SAINT EUSTATIUS AND SABA 的本地化字符串。
        /// </summary>
        public static string BQ {
            get {
                return ResourceManager.GetString("BQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BRAZIL 的本地化字符串。
        /// </summary>
        public static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BAHAMAS 的本地化字符串。
        /// </summary>
        public static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BHUTAN 的本地化字符串。
        /// </summary>
        public static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOUVET ISLAND 的本地化字符串。
        /// </summary>
        public static string BV {
            get {
                return ResourceManager.GetString("BV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOTSWANA 的本地化字符串。
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BELARUS 的本地化字符串。
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BELIZE 的本地化字符串。
        /// </summary>
        public static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CANADA 的本地化字符串。
        /// </summary>
        public static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COCOS (KEELING) ISLANDS 的本地化字符串。
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONGO, THE DEMOCRATIC REPUBLIC OF THE 的本地化字符串。
        /// </summary>
        public static string CD {
            get {
                return ResourceManager.GetString("CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CENTRAL AFRICAN REPUBLIC 的本地化字符串。
        /// </summary>
        public static string CF {
            get {
                return ResourceManager.GetString("CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONGO 的本地化字符串。
        /// </summary>
        public static string CG {
            get {
                return ResourceManager.GetString("CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWITZERLAND 的本地化字符串。
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COTE D&apos;IVOIRE 的本地化字符串。
        /// </summary>
        public static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COOK ISLANDS 的本地化字符串。
        /// </summary>
        public static string CK {
            get {
                return ResourceManager.GetString("CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHILE 的本地化字符串。
        /// </summary>
        public static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAMEROON 的本地化字符串。
        /// </summary>
        public static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHINA 的本地化字符串。
        /// </summary>
        public static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COLOMBIA 的本地化字符串。
        /// </summary>
        public static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COSTA RICA 的本地化字符串。
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CUBA 的本地化字符串。
        /// </summary>
        public static string CU {
            get {
                return ResourceManager.GetString("CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAPE VERDE 的本地化字符串。
        /// </summary>
        public static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CURACAO 的本地化字符串。
        /// </summary>
        public static string CW {
            get {
                return ResourceManager.GetString("CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHRISTMAS ISLAND 的本地化字符串。
        /// </summary>
        public static string CX {
            get {
                return ResourceManager.GetString("CX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CYPRUS 的本地化字符串。
        /// </summary>
        public static string CY {
            get {
                return ResourceManager.GetString("CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CZECH REPUBLIC 的本地化字符串。
        /// </summary>
        public static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GERMANY 的本地化字符串。
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DJIBOUTI 的本地化字符串。
        /// </summary>
        public static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DENMARK 的本地化字符串。
        /// </summary>
        public static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DOMINICA 的本地化字符串。
        /// </summary>
        public static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DOMINICAN REPUBLIC 的本地化字符串。
        /// </summary>
        public static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALGERIA 的本地化字符串。
        /// </summary>
        public static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ECUADOR 的本地化字符串。
        /// </summary>
        public static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ESTONIA 的本地化字符串。
        /// </summary>
        public static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EGYPT 的本地化字符串。
        /// </summary>
        public static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WESTERN SAHARA 的本地化字符串。
        /// </summary>
        public static string EH {
            get {
                return ResourceManager.GetString("EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERITREA 的本地化字符串。
        /// </summary>
        public static string ER {
            get {
                return ResourceManager.GetString("ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SPAIN 的本地化字符串。
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETHIOPIA 的本地化字符串。
        /// </summary>
        public static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FINLAND 的本地化字符串。
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FIJI 的本地化字符串。
        /// </summary>
        public static string FJ {
            get {
                return ResourceManager.GetString("FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FALKLAND ISLANDS (MALVINAS) 的本地化字符串。
        /// </summary>
        public static string FK {
            get {
                return ResourceManager.GetString("FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MICRONESIA, FEDERATED STATES OF 的本地化字符串。
        /// </summary>
        public static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAROE ISLANDS 的本地化字符串。
        /// </summary>
        public static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FRANCE 的本地化字符串。
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GABON 的本地化字符串。
        /// </summary>
        public static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UNITED KINGDOM 的本地化字符串。
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GRENADA 的本地化字符串。
        /// </summary>
        public static string GD {
            get {
                return ResourceManager.GetString("GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GEORGIA 的本地化字符串。
        /// </summary>
        public static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FRENCH GUIANA 的本地化字符串。
        /// </summary>
        public static string GF {
            get {
                return ResourceManager.GetString("GF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUERNSEY 的本地化字符串。
        /// </summary>
        public static string GG {
            get {
                return ResourceManager.GetString("GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GHANA 的本地化字符串。
        /// </summary>
        public static string GH {
            get {
                return ResourceManager.GetString("GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GIBRALTAR 的本地化字符串。
        /// </summary>
        public static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GREENLAND 的本地化字符串。
        /// </summary>
        public static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GAMBIA 的本地化字符串。
        /// </summary>
        public static string GM {
            get {
                return ResourceManager.GetString("GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUINEA 的本地化字符串。
        /// </summary>
        public static string GN {
            get {
                return ResourceManager.GetString("GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUADELOUPE 的本地化字符串。
        /// </summary>
        public static string GP {
            get {
                return ResourceManager.GetString("GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EQUATORIAL GUINEA 的本地化字符串。
        /// </summary>
        public static string GQ {
            get {
                return ResourceManager.GetString("GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GREECE 的本地化字符串。
        /// </summary>
        public static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS 的本地化字符串。
        /// </summary>
        public static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUATEMALA 的本地化字符串。
        /// </summary>
        public static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUAM 的本地化字符串。
        /// </summary>
        public static string GU {
            get {
                return ResourceManager.GetString("GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUINEA-BISSAU 的本地化字符串。
        /// </summary>
        public static string GW {
            get {
                return ResourceManager.GetString("GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUYANA 的本地化字符串。
        /// </summary>
        public static string GY {
            get {
                return ResourceManager.GetString("GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HONG KONG 的本地化字符串。
        /// </summary>
        public static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HEARD ISLAND AND MCDONALD ISLANDS 的本地化字符串。
        /// </summary>
        public static string HM {
            get {
                return ResourceManager.GetString("HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HONDURAS 的本地化字符串。
        /// </summary>
        public static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CROATIA 的本地化字符串。
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HAITI 的本地化字符串。
        /// </summary>
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HUNGARY 的本地化字符串。
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INDONESIA 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IRELAND 的本地化字符串。
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISRAEL 的本地化字符串。
        /// </summary>
        public static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISLE OF MAN 的本地化字符串。
        /// </summary>
        public static string IM {
            get {
                return ResourceManager.GetString("IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INDIA 的本地化字符串。
        /// </summary>
        public static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BRITISH INDIAN OCEAN TERRITORY 的本地化字符串。
        /// </summary>
        public static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IRAQ 的本地化字符串。
        /// </summary>
        public static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IRAN, ISLAMIC REPUBLIC OF 的本地化字符串。
        /// </summary>
        public static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ICELAND 的本地化字符串。
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ITALY 的本地化字符串。
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JERSEY 的本地化字符串。
        /// </summary>
        public static string JE {
            get {
                return ResourceManager.GetString("JE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JAMAICA 的本地化字符串。
        /// </summary>
        public static string JM {
            get {
                return ResourceManager.GetString("JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JORDAN 的本地化字符串。
        /// </summary>
        public static string JO {
            get {
                return ResourceManager.GetString("JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JAPAN 的本地化字符串。
        /// </summary>
        public static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KENYA 的本地化字符串。
        /// </summary>
        public static string KE {
            get {
                return ResourceManager.GetString("KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KYRGYZSTAN 的本地化字符串。
        /// </summary>
        public static string KG {
            get {
                return ResourceManager.GetString("KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAMBODIA 的本地化字符串。
        /// </summary>
        public static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KIRIBATI 的本地化字符串。
        /// </summary>
        public static string KI {
            get {
                return ResourceManager.GetString("KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COMOROS 的本地化字符串。
        /// </summary>
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAINT KITTS AND NEVIS 的本地化字符串。
        /// </summary>
        public static string KN {
            get {
                return ResourceManager.GetString("KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KOREA, DEMOCRATIC PEOPLE&apos;S REPUBLIC OF 的本地化字符串。
        /// </summary>
        public static string KP {
            get {
                return ResourceManager.GetString("KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KOREA, REPUBLIC OF 的本地化字符串。
        /// </summary>
        public static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KUWAIT 的本地化字符串。
        /// </summary>
        public static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAYMAN ISLANDS 的本地化字符串。
        /// </summary>
        public static string KY {
            get {
                return ResourceManager.GetString("KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KAZAKHSTAN 的本地化字符串。
        /// </summary>
        public static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LAO PEOPLE&apos;S DEMOCRATIC REPUBLIC 的本地化字符串。
        /// </summary>
        public static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LEBANON 的本地化字符串。
        /// </summary>
        public static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAINT LUCIA 的本地化字符串。
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LIECHTENSTEIN 的本地化字符串。
        /// </summary>
        public static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SRI LANKA 的本地化字符串。
        /// </summary>
        public static string LK {
            get {
                return ResourceManager.GetString("LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LIBERIA 的本地化字符串。
        /// </summary>
        public static string LR {
            get {
                return ResourceManager.GetString("LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LESOTHO 的本地化字符串。
        /// </summary>
        public static string LS {
            get {
                return ResourceManager.GetString("LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LITHUANIA 的本地化字符串。
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LUXEMBOURG 的本地化字符串。
        /// </summary>
        public static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LATVIA 的本地化字符串。
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LIBYAN ARAB JAMAHIRIYA 的本地化字符串。
        /// </summary>
        public static string LY {
            get {
                return ResourceManager.GetString("LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MOROCCO 的本地化字符串。
        /// </summary>
        public static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MONACO 的本地化字符串。
        /// </summary>
        public static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MOLDOVA, REPUBLIC OF 的本地化字符串。
        /// </summary>
        public static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MONTENEGRO 的本地化字符串。
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAINT MARTIN (FRENCH PART) 的本地化字符串。
        /// </summary>
        public static string MF {
            get {
                return ResourceManager.GetString("MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MADAGASCAR 的本地化字符串。
        /// </summary>
        public static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MARSHALL ISLANDS 的本地化字符串。
        /// </summary>
        public static string MH {
            get {
                return ResourceManager.GetString("MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF 的本地化字符串。
        /// </summary>
        public static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MALI 的本地化字符串。
        /// </summary>
        public static string ML {
            get {
                return ResourceManager.GetString("ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MYANMAR 的本地化字符串。
        /// </summary>
        public static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MONGOLIA 的本地化字符串。
        /// </summary>
        public static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MACAO 的本地化字符串。
        /// </summary>
        public static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NORTHERN MARIANA ISLANDS 的本地化字符串。
        /// </summary>
        public static string MP {
            get {
                return ResourceManager.GetString("MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MARTINIQUE 的本地化字符串。
        /// </summary>
        public static string MQ {
            get {
                return ResourceManager.GetString("MQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAURITANIA 的本地化字符串。
        /// </summary>
        public static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MONTSERRAT 的本地化字符串。
        /// </summary>
        public static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MALTA 的本地化字符串。
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAURITIUS 的本地化字符串。
        /// </summary>
        public static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MALDIVES 的本地化字符串。
        /// </summary>
        public static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MALAWI 的本地化字符串。
        /// </summary>
        public static string MW {
            get {
                return ResourceManager.GetString("MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MEXICO 的本地化字符串。
        /// </summary>
        public static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MALAYSIA 的本地化字符串。
        /// </summary>
        public static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MOZAMBIQUE 的本地化字符串。
        /// </summary>
        public static string MZ {
            get {
                return ResourceManager.GetString("MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NAMIBIA 的本地化字符串。
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEW CALEDONIA 的本地化字符串。
        /// </summary>
        public static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NIGER 的本地化字符串。
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NORFOLK ISLAND 的本地化字符串。
        /// </summary>
        public static string NF {
            get {
                return ResourceManager.GetString("NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NIGERIA 的本地化字符串。
        /// </summary>
        public static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NICARAGUA 的本地化字符串。
        /// </summary>
        public static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NETHERLANDS 的本地化字符串。
        /// </summary>
        public static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NORWAY 的本地化字符串。
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEPAL 的本地化字符串。
        /// </summary>
        public static string NP {
            get {
                return ResourceManager.GetString("NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NAURU 的本地化字符串。
        /// </summary>
        public static string NR {
            get {
                return ResourceManager.GetString("NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NIUE 的本地化字符串。
        /// </summary>
        public static string NU {
            get {
                return ResourceManager.GetString("NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEW ZEALAND 的本地化字符串。
        /// </summary>
        public static string NZ {
            get {
                return ResourceManager.GetString("NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OMAN 的本地化字符串。
        /// </summary>
        public static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PANAMA 的本地化字符串。
        /// </summary>
        public static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PERU 的本地化字符串。
        /// </summary>
        public static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FRENCH POLYNESIA 的本地化字符串。
        /// </summary>
        public static string PF {
            get {
                return ResourceManager.GetString("PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAPUA NEW GUINEA 的本地化字符串。
        /// </summary>
        public static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHILIPPINES 的本地化字符串。
        /// </summary>
        public static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAKISTAN 的本地化字符串。
        /// </summary>
        public static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POLAND 的本地化字符串。
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAINT PIERRE AND MIQUELON 的本地化字符串。
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PITCAIRN 的本地化字符串。
        /// </summary>
        public static string PN {
            get {
                return ResourceManager.GetString("PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PUERTO RICO 的本地化字符串。
        /// </summary>
        public static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PALESTINIAN TERRITORY, OCCUPIED 的本地化字符串。
        /// </summary>
        public static string PS {
            get {
                return ResourceManager.GetString("PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PORTUGAL 的本地化字符串。
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PALAU 的本地化字符串。
        /// </summary>
        public static string PW {
            get {
                return ResourceManager.GetString("PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PARAGUAY 的本地化字符串。
        /// </summary>
        public static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QATAR 的本地化字符串。
        /// </summary>
        public static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 REUNION 的本地化字符串。
        /// </summary>
        public static string RE {
            get {
                return ResourceManager.GetString("RE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROMANIA 的本地化字符串。
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SERBIA 的本地化字符串。
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RUSSIAN FEDERATION 的本地化字符串。
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RWANDA 的本地化字符串。
        /// </summary>
        public static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAUDI ARABIA 的本地化字符串。
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOLOMON ISLANDS 的本地化字符串。
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEYCHELLES 的本地化字符串。
        /// </summary>
        public static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SUDAN 的本地化字符串。
        /// </summary>
        public static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWEDEN 的本地化字符串。
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SINGAPORE 的本地化字符串。
        /// </summary>
        public static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA 的本地化字符串。
        /// </summary>
        public static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SLOVENIA 的本地化字符串。
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SVALBARD AND JAN MAYEN 的本地化字符串。
        /// </summary>
        public static string SJ {
            get {
                return ResourceManager.GetString("SJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SLOVAKIA 的本地化字符串。
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SIERRA LEONE 的本地化字符串。
        /// </summary>
        public static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAN MARINO 的本地化字符串。
        /// </summary>
        public static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SENEGAL 的本地化字符串。
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOMALIA 的本地化字符串。
        /// </summary>
        public static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SURINAME 的本地化字符串。
        /// </summary>
        public static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAO TOME AND PRINCIPE 的本地化字符串。
        /// </summary>
        public static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EL SALVADOR 的本地化字符串。
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SINT MAARTEN (DUTCH PART) 的本地化字符串。
        /// </summary>
        public static string SX {
            get {
                return ResourceManager.GetString("SX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SYRIAN ARAB REPUBLIC 的本地化字符串。
        /// </summary>
        public static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWAZILAND 的本地化字符串。
        /// </summary>
        public static string SZ {
            get {
                return ResourceManager.GetString("SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TURKS AND CAICOS ISLANDS 的本地化字符串。
        /// </summary>
        public static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHAD 的本地化字符串。
        /// </summary>
        public static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FRENCH SOUTHERN TERRITORIES 的本地化字符串。
        /// </summary>
        public static string TF {
            get {
                return ResourceManager.GetString("TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOGO 的本地化字符串。
        /// </summary>
        public static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THAILAND 的本地化字符串。
        /// </summary>
        public static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TAJIKISTAN 的本地化字符串。
        /// </summary>
        public static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOKELAU 的本地化字符串。
        /// </summary>
        public static string TK {
            get {
                return ResourceManager.GetString("TK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIMOR-LESTE 的本地化字符串。
        /// </summary>
        public static string TL {
            get {
                return ResourceManager.GetString("TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TURKMENISTAN 的本地化字符串。
        /// </summary>
        public static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TUNISIA 的本地化字符串。
        /// </summary>
        public static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TONGA 的本地化字符串。
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TURKEY 的本地化字符串。
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRINIDAD AND TOBAGO 的本地化字符串。
        /// </summary>
        public static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TUVALU 的本地化字符串。
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TAIWAN, PROVINCE OF CHINA 的本地化字符串。
        /// </summary>
        public static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TANZANIA, UNITED REPUBLIC OF 的本地化字符串。
        /// </summary>
        public static string TZ {
            get {
                return ResourceManager.GetString("TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UKRAINE 的本地化字符串。
        /// </summary>
        public static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UGANDA 的本地化字符串。
        /// </summary>
        public static string UG {
            get {
                return ResourceManager.GetString("UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UNITED STATES MINOR OUTLYING ISLANDS 的本地化字符串。
        /// </summary>
        public static string UM {
            get {
                return ResourceManager.GetString("UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UNITED STATES 的本地化字符串。
        /// </summary>
        public static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URUGUAY 的本地化字符串。
        /// </summary>
        public static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UZBEKISTAN 的本地化字符串。
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HOLY SEE (VATICAN CITY STATE) 的本地化字符串。
        /// </summary>
        public static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAINT VINCENT AND THE GRENADINES圣文森特和格林纳丁斯 的本地化字符串。
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VENEZUELA, BOLIVARIAN REPUBLIC OF 的本地化字符串。
        /// </summary>
        public static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIRGIN ISLANDS, BRITISH 的本地化字符串。
        /// </summary>
        public static string VG {
            get {
                return ResourceManager.GetString("VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIRGIN ISLANDS, U.S. 的本地化字符串。
        /// </summary>
        public static string VI {
            get {
                return ResourceManager.GetString("VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIET NAM 的本地化字符串。
        /// </summary>
        public static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VANUATU 的本地化字符串。
        /// </summary>
        public static string VU {
            get {
                return ResourceManager.GetString("VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WALLIS AND FUTUNA 的本地化字符串。
        /// </summary>
        public static string WF {
            get {
                return ResourceManager.GetString("WF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAMOA 的本地化字符串。
        /// </summary>
        public static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YEMEN 的本地化字符串。
        /// </summary>
        public static string YE {
            get {
                return ResourceManager.GetString("YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAYOTTE 的本地化字符串。
        /// </summary>
        public static string YT {
            get {
                return ResourceManager.GetString("YT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOUTH AFRICA 的本地化字符串。
        /// </summary>
        public static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZAMBIA 的本地化字符串。
        /// </summary>
        public static string ZM {
            get {
                return ResourceManager.GetString("ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZIMBABWE 的本地化字符串。
        /// </summary>
        public static string ZW {
            get {
                return ResourceManager.GetString("ZW", resourceCulture);
            }
        }
    }
}
